"""Baseline schema for Monitoring Maxval 0.8.5.

Revision ID: 0036
Revises: none
"""
from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa

from alembic import op

revision: str = "0036"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('failed_login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_login_attempts_ip_address'), 'failed_login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_failed_login_attempts_username'), 'failed_login_attempts', ['username'], unique=False)
    op.create_index('ix_failed_login_lookup', 'failed_login_attempts', ['username', 'ip_address', 'occurred_at'], unique=False)
    op.create_table('login_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'ip_address', name='uq_login_block_identity')
    )
    op.create_index(op.f('ix_login_blocks_blocked_until'), 'login_blocks', ['blocked_until'], unique=False)
    op.create_index(op.f('ix_login_blocks_ip_address'), 'login_blocks', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_blocks_username'), 'login_blocks', ['username'], unique=False)
    op.create_table('portal_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=False),
    sa.Column('memory_percent', sa.Float(), nullable=False),
    sa.Column('disk_percent', sa.Float(), nullable=False),
    sa.Column('uptime_seconds', sa.BigInteger(), nullable=False),
    sa.Column('bytes_sent', sa.BigInteger(), nullable=False),
    sa.Column('bytes_received', sa.BigInteger(), nullable=False),
    sa.Column('packets_sent', sa.BigInteger(), nullable=False),
    sa.Column('packets_received', sa.BigInteger(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_metrics_collected_at'), 'portal_metrics', ['collected_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('must_change_default_password', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('push_chat_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('push_incident_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('push_recovery_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_24x7', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('built_in', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('monday_start', sa.String(length=5), nullable=True),
    sa.Column('monday_end', sa.String(length=5), nullable=True),
    sa.Column('tuesday_start', sa.String(length=5), nullable=True),
    sa.Column('tuesday_end', sa.String(length=5), nullable=True),
    sa.Column('wednesday_start', sa.String(length=5), nullable=True),
    sa.Column('wednesday_end', sa.String(length=5), nullable=True),
    sa.Column('thursday_start', sa.String(length=5), nullable=True),
    sa.Column('thursday_end', sa.String(length=5), nullable=True),
    sa.Column('friday_start', sa.String(length=5), nullable=True),
    sa.Column('friday_end', sa.String(length=5), nullable=True),
    sa.Column('saturday_start', sa.String(length=5), nullable=True),
    sa.Column('saturday_end', sa.String(length=5), nullable=True),
    sa.Column('sunday_start', sa.String(length=5), nullable=True),
    sa.Column('sunday_end', sa.String(length=5), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_schedules_name'), 'work_schedules', ['name'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_created_action', 'audit_log', ['created_at', 'action'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('chat_deletion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('peer_id', sa.Integer(), nullable=False),
    sa.Column('cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['peer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_delete_pair_created', 'chat_deletion_requests', ['requester_id', 'peer_id', 'created_at'], unique=False)
    op.create_index('ix_chat_delete_peer_status', 'chat_deletion_requests', ['peer_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_deletion_requests_created_at'), 'chat_deletion_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_deletion_requests_cutoff_at'), 'chat_deletion_requests', ['cutoff_at'], unique=False)
    op.create_index(op.f('ix_chat_deletion_requests_peer_id'), 'chat_deletion_requests', ['peer_id'], unique=False)
    op.create_index(op.f('ix_chat_deletion_requests_requester_id'), 'chat_deletion_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_chat_deletion_requests_status'), 'chat_deletion_requests', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index('ix_chat_messages_pair_created', 'chat_messages', ['sender_id', 'recipient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_recipient_id'), 'chat_messages', ['recipient_id'], unique=False)
    op.create_index('ix_chat_messages_recipient_read', 'chat_messages', ['recipient_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_sender_id'), 'chat_messages', ['sender_id'], unique=False)
    op.create_table('chat_presence',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('peer_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['peer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'peer_id')
    )
    op.create_index('ix_chat_presence_peer_seen', 'chat_presence', ['peer_id', 'seen_at'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.Text(), nullable=False),
    sa.Column('auth', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', name='uq_push_subscription_endpoint')
    )
    op.create_index('ix_push_subscriptions_user', 'push_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('layout_scale', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['work_schedules.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=True)
    op.create_index(op.f('ix_sites_schedule_id'), 'sites', ['schedule_id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=300), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_created_at'), 'user_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_notifications_kind'), 'user_notifications', ['kind'], unique=False)
    op.create_index('ix_user_notifications_user_created', 'user_notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_index('ix_user_notifications_user_read', 'user_notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('monitor_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('checker_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), server_default='300', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('favorite', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_site_entry', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('layout_x', sa.Integer(), nullable=True),
    sa.Column('layout_y', sa.Integer(), nullable=True),
    sa.Column('notifications_suppressed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('unstable_pending_down', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('unstable_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('interval_seconds >= 60', name='ck_target_interval_minimum'),
    sa.CheckConstraint('port > 0 AND port <= 65535', name='ck_target_port_range'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_targets_name'), 'monitor_targets', ['name'], unique=False)
    op.create_index(op.f('ix_monitor_targets_site_id'), 'monitor_targets', ['site_id'], unique=False)
    op.create_table('check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['monitor_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_results_checked_at'), 'check_results', ['checked_at'], unique=False)
    op.create_index('ix_check_results_target_checked', 'check_results', ['target_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_check_results_target_id'), 'check_results', ['target_id'], unique=False)
    op.create_table('snmp_configs',
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.String(length=10), server_default='v2c', nullable=False),
    sa.Column('port', sa.Integer(), server_default='161', nullable=False),
    sa.Column('community_encrypted', sa.Text(), server_default='', nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), server_default='3', nullable=False),
    sa.Column('retries', sa.Integer(), server_default='1', nullable=False),
    sa.Column('ups_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_status', sa.String(length=10), server_default='never', nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('sys_name', sa.Text(), nullable=True),
    sa.Column('sys_descr', sa.Text(), nullable=True),
    sa.Column('sys_object_id', sa.String(length=255), nullable=True),
    sa.Column('sys_uptime_ticks', sa.BigInteger(), nullable=True),
    sa.Column('system_data_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('port > 0 AND port <= 65535', name='ck_snmp_config_port_range'),
    sa.CheckConstraint('retries >= 0 AND retries <= 10', name='ck_snmp_config_retries_range'),
    sa.CheckConstraint('timeout_seconds >= 1 AND timeout_seconds <= 60', name='ck_snmp_config_timeout_range'),
    sa.ForeignKeyConstraint(['target_id'], ['monitor_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_table('snmp_interfaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('if_index', sa.Integer(), nullable=False),
    sa.Column('if_name', sa.String(length=255), nullable=True),
    sa.Column('if_descr', sa.Text(), nullable=True),
    sa.Column('if_alias', sa.Text(), nullable=True),
    sa.Column('if_type', sa.Integer(), nullable=True),
    sa.Column('if_mtu', sa.Integer(), nullable=True),
    sa.Column('speed_bps', sa.BigInteger(), nullable=True),
    sa.Column('phys_address', sa.String(length=255), nullable=True),
    sa.Column('admin_status', sa.Integer(), nullable=True),
    sa.Column('oper_status', sa.Integer(), nullable=True),
    sa.Column('traffic_counter_mode', sa.String(length=16), nullable=True),
    sa.Column('in_octets', sa.String(length=32), nullable=True),
    sa.Column('out_octets', sa.String(length=32), nullable=True),
    sa.Column('traffic_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('traffic_uptime_ticks', sa.BigInteger(), nullable=True),
    sa.Column('rx_bps', sa.BigInteger(), nullable=True),
    sa.Column('tx_bps', sa.BigInteger(), nullable=True),
    sa.Column('in_errors', sa.BigInteger(), nullable=True),
    sa.Column('out_errors', sa.BigInteger(), nullable=True),
    sa.Column('in_discards', sa.BigInteger(), nullable=True),
    sa.Column('out_discards', sa.BigInteger(), nullable=True),
    sa.Column('traffic_error', sa.String(length=500), nullable=True),
    sa.Column('monitor_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('present', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.CheckConstraint('if_index > 0', name='ck_snmp_interface_index_positive'),
    sa.ForeignKeyConstraint(['target_id'], ['monitor_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'if_index', name='uq_snmp_interface_target_index')
    )
    op.create_index(op.f('ix_snmp_interfaces_target_id'), 'snmp_interfaces', ['target_id'], unique=False)
    op.create_table('snmp_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('oid', sa.String(length=255), nullable=True),
    sa.Column('source_kind', sa.String(length=16), server_default='oid', nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('unit', sa.String(length=80), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('detected_type', sa.String(length=40), nullable=True),
    sa.Column('last_value', sa.Text(), nullable=True),
    sa.Column('last_numeric_value', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('last_collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.CheckConstraint("(source_kind = 'oid' AND oid IS NOT NULL AND formula IS NULL) OR (source_kind = 'formula' AND oid IS NULL AND formula IS NOT NULL)", name='ck_snmp_metric_source'),
    sa.ForeignKeyConstraint(['target_id'], ['monitor_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'oid', name='uq_snmp_metric_target_oid')
    )
    op.create_index(op.f('ix_snmp_metrics_target_id'), 'snmp_metrics', ['target_id'], unique=False)
    op.create_table('snmp_supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('hr_device_index', sa.Integer(), nullable=False),
    sa.Column('supply_index', sa.Integer(), nullable=False),
    sa.Column('marker_index', sa.Integer(), nullable=True),
    sa.Column('colorant_index', sa.Integer(), nullable=True),
    sa.Column('supply_class', sa.Integer(), nullable=True),
    sa.Column('supply_type', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('custom_name', sa.String(length=160), nullable=True),
    sa.Column('unit_code', sa.Integer(), nullable=True),
    sa.Column('max_capacity', sa.BigInteger(), nullable=True),
    sa.Column('level', sa.BigInteger(), nullable=True),
    sa.Column('percent_remaining', sa.Float(), nullable=True),
    sa.Column('level_state', sa.String(length=20), server_default='never', nullable=False),
    sa.Column('present', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.CheckConstraint('hr_device_index > 0', name='ck_snmp_supply_hr_device_positive'),
    sa.CheckConstraint('supply_index > 0', name='ck_snmp_supply_index_positive'),
    sa.ForeignKeyConstraint(['target_id'], ['monitor_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'hr_device_index', 'supply_index', name='uq_snmp_supply_target_index')
    )
    op.create_index(op.f('ix_snmp_supplies_target_id'), 'snmp_supplies', ['target_id'], unique=False)
    op.create_table('snmp_ups_states',
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('profile', sa.String(length=32), nullable=True),
    sa.Column('battery_status', sa.Integer(), nullable=True),
    sa.Column('output_source', sa.Integer(), nullable=True),
    sa.Column('seconds_on_battery', sa.BigInteger(), nullable=True),
    sa.Column('estimated_runtime_minutes', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('battery_charge_percent', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('battery_voltage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('battery_temperature', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('battery_replace_needed', sa.Boolean(), nullable=True),
    sa.Column('last_transfer_reason', sa.String(length=255), nullable=True),
    sa.Column('last_self_test_result', sa.String(length=100), nullable=True),
    sa.Column('last_self_test_at', sa.String(length=100), nullable=True),
    sa.Column('input_lines', sa.Integer(), nullable=True),
    sa.Column('output_lines', sa.Integer(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['monitor_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('target_id')
    )
    op.create_table('target_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('checker_type', sa.String(length=50), nullable=False),
    sa.Column('address_override', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), server_default='/', nullable=False),
    sa.Column('timeout_seconds', sa.Float(), nullable=True),
    sa.Column('retries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('config_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('http_expected_status', sa.Integer(), nullable=True),
    sa.Column('http_content_contains', sa.String(length=500), nullable=True),
    sa.Column('http_content_not_contains', sa.String(length=500), nullable=True),
    sa.Column('http_max_response_ms', sa.Float(), nullable=True),
    sa.Column('tls_monitor_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('tls_warning_days', sa.Integer(), nullable=True),
    sa.Column('tls_critical_days', sa.Integer(), nullable=True),
    sa.Column('dns_name', sa.String(length=253), nullable=True),
    sa.Column('dns_record_type', sa.String(length=8), nullable=True),
    sa.Column('dns_expected_address', sa.String(length=45), nullable=True),
    sa.Column('dns_max_response_ms', sa.Float(), nullable=True),
    sa.Column('directory_path', sa.String(length=1024), nullable=True),
    sa.Column('directory_pattern', sa.String(length=255), nullable=True),
    sa.Column('directory_period_hours', sa.Float(), nullable=True),
    sa.Column('directory_show_last', sa.Integer(), nullable=True),
    sa.Column('directory_username', sa.String(length=255), nullable=True),
    sa.Column('directory_password_encrypted', sa.String(), server_default='', nullable=False),
    sa.Column('directory_last_files', sa.JSON(), nullable=True),
    sa.Column('directory_recent_count', sa.Integer(), nullable=True),
    sa.Column('directory_latest_file_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('directory_scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unstable_pending_down', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('unstable_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("dns_record_type IS NULL OR dns_record_type IN ('A', 'AAAA')", name='ck_target_check_dns_record_type'),
    sa.CheckConstraint('directory_period_hours IS NULL OR directory_period_hours > 0', name='ck_target_check_directory_period_hours'),
    sa.CheckConstraint('directory_recent_count IS NULL OR directory_recent_count >= 0', name='ck_target_check_directory_recent_count'),
    sa.CheckConstraint('directory_show_last IS NULL OR directory_show_last >= 0', name='ck_target_check_directory_show_last'),
    sa.CheckConstraint('dns_max_response_ms IS NULL OR dns_max_response_ms > 0', name='ck_target_check_dns_max_response_ms'),
    sa.CheckConstraint('http_expected_status IS NULL OR (http_expected_status >= 100 AND http_expected_status <= 599)', name='ck_target_check_http_expected_status'),
    sa.CheckConstraint('http_max_response_ms IS NULL OR http_max_response_ms > 0', name='ck_target_check_http_max_response_ms'),
    sa.CheckConstraint('port > 0 AND port <= 65535', name='ck_target_check_port_range'),
    sa.CheckConstraint('retries >= 0 AND retries <= 10', name='ck_target_check_retries_range'),
    sa.CheckConstraint('timeout_seconds IS NULL OR (timeout_seconds >= 0.5 AND timeout_seconds <= 60)', name='ck_target_check_timeout_range'),
    sa.CheckConstraint('tls_critical_days IS NULL OR tls_critical_days >= 0', name='ck_target_check_tls_critical_days'),
    sa.CheckConstraint('tls_warning_days IS NULL OR tls_critical_days IS NULL OR tls_warning_days > tls_critical_days', name='ck_target_check_tls_threshold_order'),
    sa.CheckConstraint('tls_warning_days IS NULL OR tls_warning_days > 0', name='ck_target_check_tls_warning_days'),
    sa.ForeignKeyConstraint(['target_id'], ['monitor_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_checks_target_id'), 'target_checks', ['target_id'], unique=False)
    op.create_index('ix_target_checks_target_order', 'target_checks', ['target_id', 'display_order', 'id'], unique=False)
    op.create_index('uq_target_checks_primary_per_target', 'target_checks', ['target_id'], unique=True, postgresql_where=sa.text('is_primary'), sqlite_where=sa.text('is_primary = 1'))
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_kind', sa.String(length=20), server_default='availability', nullable=False),
    sa.Column('source_key', sa.String(length=120), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message', sa.String(length=500), nullable=True),
    sa.Column('open_notification_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovery_notification_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IS NULL OR severity IN ('warning', 'critical')", name='ck_incident_severity'),
    sa.CheckConstraint("source_kind IN ('availability', 'snmp', 'check', 'check_tls')", name='ck_incident_source_kind'),
    sa.CheckConstraint("status IN ('open', 'resolved')", name='ck_incident_status'),
    sa.ForeignKeyConstraint(['check_id'], ['target_checks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_id'], ['monitor_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_check_id'), 'incidents', ['check_id'], unique=False)
    op.create_index('ix_incidents_check_status', 'incidents', ['check_id', 'status'], unique=False)
    op.create_index(op.f('ix_incidents_opened_at'), 'incidents', ['opened_at'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_target_id'), 'incidents', ['target_id'], unique=False)
    op.create_index('ix_incidents_target_source_status', 'incidents', ['target_id', 'source_kind', 'source_key', 'status'], unique=False)
    op.create_index('ix_incidents_target_status', 'incidents', ['target_id', 'status'], unique=False)
    op.create_table('snmp_interface_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rx_bps', sa.BigInteger(), nullable=True),
    sa.Column('tx_bps', sa.BigInteger(), nullable=True),
    sa.Column('in_errors', sa.BigInteger(), nullable=True),
    sa.Column('out_errors', sa.BigInteger(), nullable=True),
    sa.Column('in_discards', sa.BigInteger(), nullable=True),
    sa.Column('out_discards', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['interface_id'], ['snmp_interfaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snmp_interface_samples_interface_collected', 'snmp_interface_samples', ['interface_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_snmp_interface_samples_interface_id'), 'snmp_interface_samples', ['interface_id'], unique=False)
    op.create_table('snmp_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=30, scale=10), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['snmp_metrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snmp_samples_collected_at'), 'snmp_samples', ['collected_at'], unique=False)
    op.create_index('ix_snmp_samples_metric_collected', 'snmp_samples', ['metric_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_snmp_samples_metric_id'), 'snmp_samples', ['metric_id'], unique=False)
    op.create_table('snmp_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=True),
    sa.Column('interface_id', sa.Integer(), nullable=True),
    sa.Column('supply_id', sa.Integer(), nullable=True),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=4), nullable=False),
    sa.Column('warning_value', sa.Float(), nullable=True),
    sa.Column('critical_value', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('current_level', sa.String(length=16), server_default='normal', nullable=False),
    sa.Column('last_value', sa.Float(), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(source_kind = 'metric' AND metric_id IS NOT NULL AND interface_id IS NULL AND supply_id IS NULL AND field = 'value') OR (source_kind = 'interface' AND interface_id IS NOT NULL AND metric_id IS NULL AND supply_id IS NULL AND field IN ('rx_bps', 'tx_bps', 'errors_delta', 'discards_delta')) OR (source_kind = 'supply' AND supply_id IS NOT NULL AND metric_id IS NULL AND interface_id IS NULL AND field = 'percent') OR (source_kind = 'ups' AND metric_id IS NULL AND interface_id IS NULL AND supply_id IS NULL AND field IN ('battery_charge_percent', 'estimated_runtime_minutes', 'battery_voltage', 'battery_temperature', 'input_voltage:1', 'input_voltage:2', 'input_voltage:3', 'output_voltage:1', 'output_voltage:2', 'output_voltage:3', 'input_current:1', 'input_current:2', 'input_current:3', 'output_current:1', 'output_current:2', 'output_current:3', 'output_load_percent:1', 'output_load_percent:2', 'output_load_percent:3'))", name='ck_snmp_threshold_source'),
    sa.CheckConstraint("current_level IN ('normal', 'warning', 'critical')", name='ck_snmp_threshold_level'),
    sa.CheckConstraint("operator IN ('gt', 'lt')", name='ck_snmp_threshold_operator'),
    sa.CheckConstraint("source_kind IN ('metric', 'interface', 'supply', 'ups')", name='ck_snmp_threshold_source_kind'),
    sa.CheckConstraint('warning_value IS NOT NULL OR critical_value IS NOT NULL', name='ck_snmp_threshold_has_value'),
    sa.ForeignKeyConstraint(['interface_id'], ['snmp_interfaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['snmp_metrics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supply_id'], ['snmp_supplies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['monitor_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snmp_thresholds_interface_id'), 'snmp_thresholds', ['interface_id'], unique=False)
    op.create_index(op.f('ix_snmp_thresholds_metric_id'), 'snmp_thresholds', ['metric_id'], unique=False)
    op.create_index(op.f('ix_snmp_thresholds_supply_id'), 'snmp_thresholds', ['supply_id'], unique=False)
    op.create_index('ix_snmp_thresholds_target_enabled', 'snmp_thresholds', ['target_id', 'enabled'], unique=False)
    op.create_index(op.f('ix_snmp_thresholds_target_id'), 'snmp_thresholds', ['target_id'], unique=False)
    op.create_table('snmp_ups_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('event_key', sa.String(length=40), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['snmp_ups_states.target_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snmp_ups_events_target_collected', 'snmp_ups_events', ['target_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_snmp_ups_events_target_id'), 'snmp_ups_events', ['target_id'], unique=False)
    op.create_table('snmp_ups_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('line_index', sa.Integer(), nullable=False),
    sa.Column('voltage', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('frequency', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('current', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('power', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('load_percent', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['snmp_ups_states.target_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_id', 'direction', 'line_index', name='uq_snmp_ups_line')
    )
    op.create_index(op.f('ix_snmp_ups_lines_target_id'), 'snmp_ups_lines', ['target_id'], unique=False)
    op.create_table('snmp_ups_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=80), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['snmp_ups_states.target_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_snmp_ups_samples_target_id'), 'snmp_ups_samples', ['target_id'], unique=False)
    op.create_index('ix_snmp_ups_samples_target_metric_collected', 'snmp_ups_samples', ['target_id', 'metric_key', 'collected_at'], unique=False)
    op.create_table('target_check_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('config_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tls_not_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tls_days_remaining', sa.Float(), nullable=True),
    sa.Column('tls_health', sa.String(length=16), nullable=True),
    sa.CheckConstraint("tls_health IS NULL OR tls_health IN ('ok', 'warning', 'critical')", name='ck_target_check_result_tls_health'),
    sa.ForeignKeyConstraint(['check_id'], ['target_checks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_target_check_results_check_checked', 'target_check_results', ['check_id', 'checked_at'], unique=False)
    op.create_index(op.f('ix_target_check_results_check_id'), 'target_check_results', ['check_id'], unique=False)
    op.create_index(op.f('ix_target_check_results_checked_at'), 'target_check_results', ['checked_at'], unique=False)
    # Fresh installations start with the same static defaults as the 0.8.5
    # application. Runtime and operational data is deliberately not seeded.
    settings = [
        ("default_check_interval_seconds", "300", "Типовой интервал проверки объектов в секундах"),
        ("failures_before_incident", "2", "Количество неудач до подтверждения инцидента"),
        ("history_retention_days", "90", "Срок хранения подробных результатов проверок"),
        ("notifications_enabled", "true", "Глобальный переключатель внешних каналов уведомлений"),
        ("smtp_enabled", "true", "Использовать SMTP для автоматических уведомлений"),
        ("smtp_host", "", "SMTP-сервер"),
        ("smtp_port", "587", "SMTP-порт"),
        ("smtp_username", "", "SMTP-логин"),
        ("smtp_password", "", "Зашифрованный SMTP-пароль"),
        ("smtp_sender", "", "Адрес отправителя"),
        ("smtp_recipient", "", "Адрес получателя"),
        ("smtp_starttls", "true", "Использовать STARTTLS"),
        ("display_timezone", "Europe/Moscow", "Часовой пояс IANA для всех дат интерфейса"),
        ("portal_metric_interval_seconds", "60", "Интервал записи состояния портала в секундах"),
        ("portal_metric_retention_hours", "168", "Срок хранения показателей портала в часах"),
        ("target_history_max_results", "1000", "Максимум результатов объекта для статистики и графика"),
        ("audit_retention_days", "7", "Срок хранения журнала аудита в днях"),
        ("notification_retention_days", "30", "Срок хранения внутренних оповещений в днях"),
        ("https_enabled", "false", "HTTPS включён"),
        ("https_redirect_http", "false", "Перенаправлять HTTP на HTTPS"),
        ("tls_expiry_warning_enabled", "false", "Предупреждать об окончании TLS-сертификата"),
        ("tls_expiry_warning_days", "14", "За сколько дней предупреждать об окончании TLS-сертификата"),
        ("snmp_sample_retention_days", "30", "Срок хранения числовой истории SNMP в днях"),
        ("snmp_sample_max_per_target", "1000", "Максимум числовых SNMP samples на объект"),
        ("availability_warning_threshold_percent", "1", "Нижняя граница жёлтой доступности за 24 часа, %"),
        ("availability_good_threshold_percent", "100", "Нижняя граница зелёной доступности за 24 часа, %"),
        ("min_password_length", "8", "Минимальная длина нового пароля (от 3 до 64)"),
    ]
    seeded_at = datetime.now(UTC)
    op.bulk_insert(
        sa.table(
            "work_schedules",
            sa.column("id", sa.Integer),
            sa.column("name", sa.String),
            sa.column("is_24x7", sa.Boolean),
            sa.column("built_in", sa.Boolean),
            sa.column("created_at", sa.DateTime(timezone=True)),
            sa.column("updated_at", sa.DateTime(timezone=True)),
        ),
        [{
            "id": 0,
            "name": "Круглосуточно",
            "is_24x7": True,
            "built_in": True,
            "created_at": seeded_at,
            "updated_at": seeded_at,
        }],
    )
    op.bulk_insert(
        sa.table(
            "app_settings",
            sa.column("key", sa.String),
            sa.column("value", sa.String),
            sa.column("description", sa.String),
            sa.column("created_at", sa.DateTime(timezone=True)),
            sa.column("updated_at", sa.DateTime(timezone=True)),
        ),
        [
            {
                "key": key,
                "value": value,
                "description": description,
                "created_at": seeded_at,
                "updated_at": seeded_at,
            }
            for key, value, description in settings
        ],
        multiinsert=False,
    )
    op.bulk_insert(
        sa.table(
            "users",
            sa.column("username", sa.String),
            sa.column("password_hash", sa.String),
            sa.column("role", sa.String),
            sa.column("active", sa.Boolean),
            sa.column("must_change_default_password", sa.Boolean),
            sa.column("push_chat_enabled", sa.Boolean),
            sa.column("push_incident_enabled", sa.Boolean),
            sa.column("push_recovery_enabled", sa.Boolean),
            sa.column("created_at", sa.DateTime(timezone=True)),
            sa.column("updated_at", sa.DateTime(timezone=True)),
        ),
        [{
            "username": "admin",
            "password_hash": "$argon2id$v=19$m=65536,t=3,p=4$e7qAAoi13mYP2aLVHpNCBw$cTl2kFqVed01FGvsJIeKsVZgRC9LCSDYZ0wT/T6GDvQ",
            "role": "admin",
            "active": True,
            "must_change_default_password": True,
            "push_chat_enabled": True,
            "push_incident_enabled": True,
            "push_recovery_enabled": True,
            "created_at": seeded_at,
            "updated_at": seeded_at,
        }],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_check_results_checked_at'), table_name='target_check_results')
    op.drop_index(op.f('ix_target_check_results_check_id'), table_name='target_check_results')
    op.drop_index('ix_target_check_results_check_checked', table_name='target_check_results')
    op.drop_table('target_check_results')
    op.drop_index('ix_snmp_ups_samples_target_metric_collected', table_name='snmp_ups_samples')
    op.drop_index(op.f('ix_snmp_ups_samples_target_id'), table_name='snmp_ups_samples')
    op.drop_table('snmp_ups_samples')
    op.drop_index(op.f('ix_snmp_ups_lines_target_id'), table_name='snmp_ups_lines')
    op.drop_table('snmp_ups_lines')
    op.drop_index(op.f('ix_snmp_ups_events_target_id'), table_name='snmp_ups_events')
    op.drop_index('ix_snmp_ups_events_target_collected', table_name='snmp_ups_events')
    op.drop_table('snmp_ups_events')
    op.drop_index(op.f('ix_snmp_thresholds_target_id'), table_name='snmp_thresholds')
    op.drop_index('ix_snmp_thresholds_target_enabled', table_name='snmp_thresholds')
    op.drop_index(op.f('ix_snmp_thresholds_supply_id'), table_name='snmp_thresholds')
    op.drop_index(op.f('ix_snmp_thresholds_metric_id'), table_name='snmp_thresholds')
    op.drop_index(op.f('ix_snmp_thresholds_interface_id'), table_name='snmp_thresholds')
    op.drop_table('snmp_thresholds')
    op.drop_index(op.f('ix_snmp_samples_metric_id'), table_name='snmp_samples')
    op.drop_index('ix_snmp_samples_metric_collected', table_name='snmp_samples')
    op.drop_index(op.f('ix_snmp_samples_collected_at'), table_name='snmp_samples')
    op.drop_table('snmp_samples')
    op.drop_index(op.f('ix_snmp_interface_samples_interface_id'), table_name='snmp_interface_samples')
    op.drop_index('ix_snmp_interface_samples_interface_collected', table_name='snmp_interface_samples')
    op.drop_table('snmp_interface_samples')
    op.drop_index('ix_incidents_target_status', table_name='incidents')
    op.drop_index('ix_incidents_target_source_status', table_name='incidents')
    op.drop_index(op.f('ix_incidents_target_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_opened_at'), table_name='incidents')
    op.drop_index('ix_incidents_check_status', table_name='incidents')
    op.drop_index(op.f('ix_incidents_check_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('uq_target_checks_primary_per_target', table_name='target_checks', postgresql_where=sa.text('is_primary'), sqlite_where=sa.text('is_primary = 1'))
    op.drop_index('ix_target_checks_target_order', table_name='target_checks')
    op.drop_index(op.f('ix_target_checks_target_id'), table_name='target_checks')
    op.drop_table('target_checks')
    op.drop_table('snmp_ups_states')
    op.drop_index(op.f('ix_snmp_supplies_target_id'), table_name='snmp_supplies')
    op.drop_table('snmp_supplies')
    op.drop_index(op.f('ix_snmp_metrics_target_id'), table_name='snmp_metrics')
    op.drop_table('snmp_metrics')
    op.drop_index(op.f('ix_snmp_interfaces_target_id'), table_name='snmp_interfaces')
    op.drop_table('snmp_interfaces')
    op.drop_table('snmp_configs')
    op.drop_index(op.f('ix_check_results_target_id'), table_name='check_results')
    op.drop_index('ix_check_results_target_checked', table_name='check_results')
    op.drop_index(op.f('ix_check_results_checked_at'), table_name='check_results')
    op.drop_table('check_results')
    op.drop_index(op.f('ix_monitor_targets_site_id'), table_name='monitor_targets')
    op.drop_index(op.f('ix_monitor_targets_name'), table_name='monitor_targets')
    op.drop_table('monitor_targets')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expires_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_user_notifications_user_read', table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_index('ix_user_notifications_user_created', table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_kind'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_created_at'), table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index(op.f('ix_sites_schedule_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index('ix_push_subscriptions_user', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('ix_chat_presence_peer_seen', table_name='chat_presence')
    op.drop_table('chat_presence')
    op.drop_index(op.f('ix_chat_messages_sender_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_recipient_read', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_recipient_id'), table_name='chat_messages')
    op.drop_index('ix_chat_messages_pair_created', table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_deletion_requests_status'), table_name='chat_deletion_requests')
    op.drop_index(op.f('ix_chat_deletion_requests_requester_id'), table_name='chat_deletion_requests')
    op.drop_index(op.f('ix_chat_deletion_requests_peer_id'), table_name='chat_deletion_requests')
    op.drop_index(op.f('ix_chat_deletion_requests_cutoff_at'), table_name='chat_deletion_requests')
    op.drop_index(op.f('ix_chat_deletion_requests_created_at'), table_name='chat_deletion_requests')
    op.drop_index('ix_chat_delete_peer_status', table_name='chat_deletion_requests')
    op.drop_index('ix_chat_delete_pair_created', table_name='chat_deletion_requests')
    op.drop_table('chat_deletion_requests')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_created_action', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_work_schedules_name'), table_name='work_schedules')
    op.drop_table('work_schedules')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_portal_metrics_collected_at'), table_name='portal_metrics')
    op.drop_table('portal_metrics')
    op.drop_index(op.f('ix_login_blocks_username'), table_name='login_blocks')
    op.drop_index(op.f('ix_login_blocks_ip_address'), table_name='login_blocks')
    op.drop_index(op.f('ix_login_blocks_blocked_until'), table_name='login_blocks')
    op.drop_table('login_blocks')
    op.drop_index('ix_failed_login_lookup', table_name='failed_login_attempts')
    op.drop_index(op.f('ix_failed_login_attempts_username'), table_name='failed_login_attempts')
    op.drop_index(op.f('ix_failed_login_attempts_ip_address'), table_name='failed_login_attempts')
    op.drop_table('failed_login_attempts')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
